### ISSUE TITLE
Sources for HMMs for gene hits in LithoGenie

### ISSUE THREAD

**Issue by rachelmugge** [Arkadiy-Garber/MagicLamp#10]
Hi,
I am trying to track down the source of HMMs for each gene hit within my dataset after running LithoGenie, and I was able to find most of them in the supplementary info for this paper: https://www.nature.com/articles/ncomms13219 

However, I couldn't find sources for a handful of HMMs, listed here:
[lithogenie_hits_unknown_hmm_source.xlsx](https://github.com/Arkadiy-Garber/MagicLamp/files/9385681/lithogenie_hits_unknown_hmm_source.xlsx)

I've searched the "hmms" folder on here also and while I found the hmm files, they did not list the accession number- where can I find this information?

Thank you!

**Comment by Arkadiy-Garber** [comment]
Hey! Those HMMs without accessions are custom-made specifically for this software. As in the HMMs from Anantharaman et al, my custom-made HMMs were compared against a reference database (nr) to calibrate an appropriate bit score cutoff for each.

**Comment by rachelmugge** [comment]
Ah okay, got it! So for the custom HMMs within MagicLamp (LithoGenie), I assume they were created using the same method as detailed in your FeGenie paper? (https://www.frontiersin.org/articles/10.3389/fmicb.2020.00037/full?ref=https://githubhelp.com#S9) Great methods section, by the way. Just wanting to give appropriate credit!

**Comment by Arkadiy-Garber** [comment]
Thanks, Rachel! I appreciate you sayin that.

Yes - any custom-made HMMs in MagicLamp were made using the same method as that described in the FeGenie paper.

**Comment by seanmcallister** [comment]
Seems like this can be closed?

**Comment by rachelmugge** [comment]
Yes, this info was helpful. Thank you!
