### ISSUE TITLE
R figure output when running the YfGenie.py

### ISSUE THREAD

**Issue by azam17** [Arkadiy-Garber/MagicLamp#14]
Hi, how do we get the R figure when running the YfGenie.py? im just using the existing hmm inside the hmms folder

**Comment by Arkadiy-Garber** [comment]
Hi, thanks for your interest in MagicLamp! Unfortunately, the recent update of this software removes its ability to automatically generate plots. That feature was very buggy and clunky, and I consider the main output files to be the CSV files.

If you'd like to generate similar R plots, all the R code to do so is present in this location: [RSCRIPTS](https://github.com/Arkadiy-Garber/MagicLamp/tree/master/rscripts). Sorry for the bad naming of variables (these scripts were originally written for FeGenie). But you should be able to plug in the output CSV files into this.

Let me know if you have any questions, and sorry for the inconvenience.
Arkadiy

**Comment by azam17** [comment]
okay thanks for the reply. i will try using the R codes.

**Comment by Arkadiy-Garber** [comment]
Sounds good. Let me know if you have any other issues.

Cheers,
Arkadiy

**Comment by azam17** [comment]
I have a question which is irrelevant to the original question. When using a fasta file as an input, is it required to include both the gff file and the protein sequence in fasta format file?

**Comment by Arkadiy-Garber** [comment]
Yup, all three file types are mandatory input.

I recommend using Prokka or Bakta to generate the gff file and protein sequences.

https://github.com/oschwengers/bakta

https://github.com/tseemann/prokka
