### ISSUE TITLE
Potential setup issue

### ISSUE THREAD

**Issue by susheelbhanu** [Arkadiy-Garber/MagicLamp#2]
Hey @Arkadiy-Garber 

I was trying to re-setup MagicLamp and noticed the following potential issue. In the `setup.sh` script which looks like so:
```
conda create -n fegenie -c r r-ggplot2 r-stringi r-reshape r-reshape2 r-tidyverse r-argparse r-ggdendro r-pvclust python=3.7 hmmer diamond prodigal blast metabat2 --yes

## activating environment
source activate magiccave
```

Line #11 creates a conda environment called "`fegenie`". However, lines #18 and 49 are activating an environment called "`magiccave`"

**ERROR**
```
# To activate this environment, use
#
#     $ conda activate fegenie
#
# To deactivate an active environment, use
#
#     $ conda deactivate

setup.sh: line 13: Rscript: command not found
setup.sh: line 14: Rscript: command not found
setup.sh: line 15: Rscript: command not found
setup.sh: line 18: activate: No such file or directory
mkdir: cannot create directory ‘/etc/conda’: Permission denied
setup.sh: line 46: /etc/conda/activate.d/env_vars.sh: No such file or directory
setup.sh: line 49: activate: No such file or directory

        DONE!
```
Thanks again for a great pipeline!

**Comment by Arkadiy-Garber** [comment]
Hi Susheel,

Thanks for your interest in MagicLamp! and Thanks for letting me know about this issue. I see there is a typo in the setup.sh script. I just fixed this ,and re-named the conda environment to magiclamp. If you re-run `bash setup.sh`, this error should be resolved. Let me know if you have any questions or run into any other issues.

Thanks!
Arkadiy

**Comment by susheelbhanu** [comment]
Thanks @Arkadiy-Garber!
