### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by 18AS** [Arkadiy-Garber/MagicLamp#3]
Hi! I was trying to run MagicLamp. However, it shows an error, suggesting conda environment is not there. Please help. 

Is it possible to get some

**Comment by Arkadiy-Garber** [comment]
Hi,

Thanks for your interest in MagicLamp! Sorry about the error. There was a bug/typo in the setup.sh script. Could you please try re-running that script `bash setup.sh` and try again. I re-named the conda environment to 'magiclamp'. So you can invoke it with `conda activate magiclamp` or `source activate magiclamp`

**Comment by 18AS** [comment]
Thanks for your quick response.
It is showing the below mentioned error. 
![Error 2](https://user-images.githubusercontent.com/80035334/120905894-d1997a80-c672-11eb-802b-a22db0c5fa33.PNG)

**Comment by Arkadiy-Garber** [comment]
Hi @18AS,

Have you gotten around this issue? The script has been updated, so this error should be avoided.

Thanks,
Arkadiy
