### ISSUE TITLE
WspGenie error writing heatmap

### ISSUE THREAD

**Issue by rachelmugge** [Arkadiy-Garber/MagicLamp#8]
Hello,
I am running WspGenie, and everything went well except for the very last step of writing the heatmap, which gave this error:

Traceback (most recent call last):
  File "/Users/firefly-hl/MagicLamp/MagicLamp.py", line 36, in <module>
    WspGenie.main()
  File "/Users/firefly-hl/MagicLamp/genies/WspGenie.py", line 1064, in main
    outHeat.write(str((len(Dict[j][i]) / int(normDict[j])) * float(100)) + ",")
TypeError: int() argument must be a string, a bytes-like object or a number, not 'collections.defaultdict'

Any advice on how to resolve this?

Thank you!

**Comment by Arkadiy-Garber** [comment]
Hey Rachel,

Thanks for your interested in MagicLamp! Happy to help you troubleshoot this issue.

Could you please share the command that you used to run wspgenie? Also, if possible, it would be helpful for me to see the wspgenie-summary.csv file.

Thanks!
Arkadiy

**Comment by rachelmugge** [comment]
Hi- wow that was fast!

Sure- here is the command:

`MagicLamp.py WspGenie -bin_dir /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_analysis/pipeline_4_assembly_based_func_annot/04_pullseq_scaffolds_500bp -bin_ext fasta -out /Volumes/FireFly_Promise_Pegasus/RMugge/DISSERTATION/Ch3/Metagenome_analysis/pipeline_4_assembly_based_func_annot/07_WspGenie --norm --meta --makeplots -t 6`

[wspgenie-summary.csv](https://github.com/Arkadiy-Garber/MagicLamp/files/9270475/wspgenie-summary.csv)

^This should be the summary.csv file, hopefully that works (first time sharing a file via GitHub!)

**Comment by Arkadiy-Garber** [comment]
Hi Rachel,

Thanks for providing that info. I believe I located the bug responsible for this error, and updated the script. Please do a fresh `git clone https://github.com/Arkadiy-Garber/MagicLamp.git` and re-run the command.

Good luck with your research! And don't hesitate to reach out if you have questions or any other issues.

Cheers,
Arkadiy

**Comment by rachelmugge** [comment]
The pipeline just finished with the new script and all went well! Thank you so much!

**Comment by Arkadiy-Garber** [comment]
Awesome, glad the fix worked! Have a good weekend :)
